Use Azure Storage Accounts as terraform backend
spring-cloud-services-samples/acme_fitness_demo pull request #16
Opened 2022-04-29 16:13 UTC by kvmw

2022-05-02 18:58 UTC, maly7 approved these changes
Thanks, @kvmw! This looks good. Would you explain what setup and commands you used to create the storage account?

2022-05-02 20:02 UTC, maly7 requested changes

2022-05-02 20:02 UTC, maly7 commented on terraform/main.tf
> +  name         = "admin-username"
This key vault secret should be named `POSTGRES-LOGIN-NAME` to match what the applications expect as seen [here](https://github.com/Azure-Samples/acme-fitness-store#create-azure-key-vault-and-store-secrets)

2022-05-02 20:02 UTC, maly7 commented on terraform/main.tf
> +  name         = "admin-password"
Same thing here, but this should be `POSTGRES-LOGIN-PASSWORD`

2022-05-03 08:52 UTC, kvmw commented
> Thanks, @kvmw! This looks good. Would you explain what setup and commands you used to create the storage account?

Since this was a one time job, I did via portal.
Create a new Storage Account: https://portal.azure.com/#blade/HubsExtension/BrowseResource/resourceType/Microsoft.Storage%2FStorageAccounts

In the newly created  storage account, add a new container with the desired name.

2022-05-03 20:00 UTC, maly7 approved these changes

2022-05-04 07:17 UTC, merged